CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.DRIVERS AS
SELECT 
   	DRIVERID,
	CONCAT(FORENAME, ' ', SURNAME) AS FULL_NAME,
	DOB,
	NATIONALITY
FROM 
 EVENT.DATATHON_2025_TEAM_ETA.DRIVERS;

-- ALTER TABLE EVENT.DATATHON_2025_TEAM_ETA.DRIVERS
-- ADD COLUMN WINS INT;

-- UPDATE EVENT.DATATHON_2025_TEAM_ETA.DRIVERS D
-- SET WINS = (
--     SELECT COUNT(*)
--     FROM EVENT.DATATHON_2025_TEAM_ETA.RESULTS R
--     WHERE R.DRIVERID = D.DRIVERID
--       AND R.POSITIONORDER = 1
-- );

