-- SQL script to copy the  tables from playground.datathon to event.datathon_2025_team_eta

-- Create a clone of the table in the target location
CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.CIRCUITS 
AS SELECT * FROM PLAYGROUND.DATATHON.CIRCUITS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.CIRCUITS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.CIRCUITS;



CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTORS 
AS SELECT * FROM PLAYGROUND.DATATHON.CONSTRUCTORS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.CONSTRUCTORS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTORS;


CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.DRIVERS 
AS SELECT * FROM PLAYGROUND.DATATHON.DRIVERS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.DRIVERS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.DRIVERS;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.LAP_TIMES 
AS SELECT * FROM PLAYGROUND.DATATHON.LAP_TIMES;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.LAP_TIMES
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.LAP_TIMES;


CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.PIT_STOPS 
AS SELECT * FROM PLAYGROUND.DATATHON.PIT_STOPS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.PIT_STOPS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.PIT_STOPS;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.QUALIFYING 
AS SELECT * FROM PLAYGROUND.DATATHON.QUALIFYING;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.QUALIFYING
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.QUALIFYING;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.RACES 
AS SELECT * FROM PLAYGROUND.DATATHON.RACES;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.RACES
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.RACES;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.RESULTS 
AS SELECT * FROM PLAYGROUND.DATATHON.RESULTS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.RESULTS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.RESULTS;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.SEASONS 
AS SELECT * FROM PLAYGROUND.DATATHON.SEASONS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.SEASONS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.SEASONS;

CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.SPRINT_RESULTS 
AS SELECT * FROM PLAYGROUND.DATATHON.SPRINT_RESULTS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.SPRINT_RESULTS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.SPRINT_RESULTS;


CREATE OR REPLACE TABLE EVENT.DATATHON_2025_TEAM_ETA.STATUS 
AS SELECT * FROM PLAYGROUND.DATATHON.STATUS;

-- Verify row count
SELECT 'Source table row count: ' AS description, COUNT(*) AS row_count 
FROM PLAYGROUND.DATATHON.STATUS
UNION ALL
SELECT 'Target table row count: ' AS description, COUNT(*) AS row_count 
FROM EVENT.DATATHON_2025_TEAM_ETA.STATUS;