CREATE OR REPLACE VIEW EVENT.DATATHON_2025_TEAM_ETA.CIRCUIT_STATISTICS AS
SELECT 
    c.CIRCUITID,
    c.NAME as CIRCUIT_NAME,
    c.LOCATION,
    c.COUNTRY,
    c.ESTIMATED_LENGTH_KM,
    c.AVG_RACE_LAPS,
    c.ESTIMATED_RACE_DISTANCE_KM,
    COUNT(DISTINCT md.RACEID) as races_held,
    COUNT(DISTINCT md.DRIVERID) as unique_drivers,
    COUNT(DISTINCT md.CONSTRUCTORID) as unique_constructors,
    AVG(md.POINTS) as avg_points_awarded,
    MAX(md.FASTESTLAPSPEED) as max_lap_speed,
    COUNT(CASE WHEN md.DNF = TRUE THEN 1 END) as total_dnfs,
    ROUND(COUNT(CASE WHEN md.DNF = TRUE THEN 1 END) * 100.0 / COUNT(*), 2) as dnf_percentage
FROM EVENT.DATATHON_2025_TEAM_ETA.CIRCUITS c
JOIN EVENT.DATATHON_2025_TEAM_ETA.RACES r ON c.CIRCUITID = r.CIRCUITID
JOIN EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTOR_DRIVER_RACE_STATUS md ON r.RACEID = md.RACEID
WHERE r.YEAR >= 2014
GROUP BY c.CIRCUITID, c.NAME, c.LOCATION, c.COUNTRY, c.ESTIMATED_LENGTH_KM, c.AVG_RACE_LAPS, c.ESTIMATED_RACE_DISTANCE_KM
ORDER BY races_held DESC, dnf_percentage DESC