CREATE OR REPLACE VIEW EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTOR_PERFORMANCE AS
SELECT 
    CONSTRUCTORID,
    CONSTRUCTOR_NAME,
    CONSTRUCTOR_NATIONALITY,
    COUNT(DISTINCT RACEID) as races_entered,
    SUM(POINTS) as total_points,
    COUNT(CASE WHEN POSITIONORDER = 1 THEN 1 END) as wins,
    COUNT(CASE WHEN POSITIONORDER <= 3 THEN 1 END) as podiums,
    ROUND(AVG(POSITIONORDER), 2) as avg_finish_position,
    YEAR
FROM EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTOR_DRIVER_RACE_STATUS
WHERE YEAR >= 2014
GROUP BY CONSTRUCTORID, CONSTRUCTOR_NAME, CONSTRUCTOR_NATIONALITY, YEAR
ORDER BY YEAR DESC, total_points DESC