CREATE OR REPLACE VIEW EVENT.DATATHON_2025_TEAM_ETA.DRIVER_PERFORMANCE AS
SELECT 
    DRIVERID, 
    FULL_NAME,
    DRIVER_NATIONALITY,
    COUNT(DISTINCT RACEID) as races_entered,
    SUM(POINTS) as total_points,
    COUNT(CASE WHEN POSITIONORDER = 1 THEN 1 END) as wins,
    COUNT(CASE WHEN POSITIONORDER <= 3 THEN 1 END) as podiums,
    COUNT(CASE WHEN DNF = TRUE THEN 1 END) as dnfs,
    ROUND(AVG(GRID), 2) as avg_grid_position,
    ROUND(AVG(POSITIONORDER), 2) as avg_finish_position
FROM EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTOR_DRIVER_RACE_STATUS
WHERE YEAR >= 2014
GROUP BY DRIVERID, FULL_NAME, DRIVER_NATIONALITY
ORDER BY total_points DESC