CREATE OR REPLACE VIEW EVENT.DATATHON_2025_TEAM_ETA.DRIVER_PROGRESSION AS
SELECT 
    d.DRIVERID,
    d.FULL_NAME,
    r.YEAR,
    COUNT(DISTINCT res.RACEID) as races,
    SUM(res.POINTS) as season_points,
    COUNT(CASE WHEN res.POSITIONORDER = 1 THEN 1 END) as wins,
    COUNT(CASE WHEN res.POSITIONORDER <= 3 THEN 1 END) as podiums,
    COUNT(CASE WHEN res.DNF = TRUE THEN 1 END) as dnfs,
    ROUND(AVG(res.GRID), 2) as avg_grid,
    ROUND(AVG(res.POSITIONORDER), 2) as avg_finish,
    ROUND(AVG(res.GRID - res.POSITIONORDER), 2) as avg_positions_gained
FROM EVENT.DATATHON_2025_TEAM_ETA.DRIVERS d
JOIN EVENT.DATATHON_2025_TEAM_ETA.RESULTS res ON d.DRIVERID = res.DRIVERID
JOIN EVENT.DATATHON_2025_TEAM_ETA.RACES r ON res.RACEID = r.RACEID
WHERE r.YEAR >= 2014
GROUP BY d.DRIVERID, d.FULL_NAME, r.YEAR
ORDER BY d.FULL_NAME, r.YEAR