CREATE OR REPLACE VIEW EVENT.DATATHON_2025_TEAM_ETA.RACE_WINNERS AS
SELECT 
    r.YEAR, 
    r.RACE_NAME, 
    r.DATE,
    d.FULL_NAME as DRIVER_NAME, 
    d.DRIVER_NATIONALITY,
    c.CONSTRUCTOR_NAME, 
    c.CONSTRUCTOR_NATIONALITY,
    res.POINTS, 
    res.LAPS, 
    res.FASTESTLAPTIME,
    res.GRID as STARTING_POSITION,
    (res.GRID - 1) as POSITIONS_GAINED
FROM EVENT.DATATHON_2025_TEAM_ETA.RESULTS res
JOIN EVENT.DATATHON_2025_TEAM_ETA.RACES r ON res.RACEID = r.RACEID
JOIN EVENT.DATATHON_2025_TEAM_ETA.DRIVERS d ON res.DRIVERID = d.DRIVERID
JOIN EVENT.DATATHON_2025_TEAM_ETA.CONSTRUCTORS c ON res.CONSTRUCTORID = c.CONSTRUCTORID
WHERE res.POSITIONORDER = 1
AND r.YEAR >= 2014
ORDER BY r.YEAR DESC, r.DATE DESC